---
extends: default

rules:
  line-length:
    max: 256
    level: warning
  truthy:
    forbid-implicit-flow-mapping: false
    allowed-values: ["true", "false", "on"]
    check-keys: false
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  document-start:
    present: true
  indentation:
    spaces: 2
    indent-sequences: true
