ALTER TABLE blueprints
  ADD COLUMN IF NOT EXISTS image          TEXT  NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS env            JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ports          JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS outputs        JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS runtime_hints  JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS startup_script TEXT  NOT NULL DEFAULT '';
