---
name: Action Lint
"on":
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  actionlint:
    name: Action Lint
    uses: kleffio/.github/.github/workflows/_actionlint.yml@main