---
name: Go Lint
"on":
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  golangci-lint:
    name: Go Lint
    uses: kleffio/.github/.github/workflows/_golangci-lint.yml@main
