---
name: YAML Lint
"on":
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  yamllint:
    name: YAML Lint
    uses: kleffio/.github/.github/workflows/_yaml-lint.yml@main
    